name: Build and upload

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
        pnpm install

    - name: build
      run: pnpm run build

    # - name: Run Unit Tests
    #   run: pnpm test

    - name: Upload build to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          whoami
          rsync -av --delete ./dist/ ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/home/kevin/bnscreenshare/

    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2.5.1
    #   with:
    #     key: ${{ secrets.SSH_KEY }}
    #     known_hosts: "poggers"

    # - name: Copy build directory to server
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    #   run: |
    #     rsync -av --delete ./dist/ ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/home/kevin/bnscreenshare/
